export {
  ActionEngineError,
  actionAttackBonusTarget,
  actionDamageModifierTarget,
  actionStateKey,
  applyActionResourceCosts,
  parseActionGrantPayload,
  resolveActions,
} from "./actions.ts"
export {
  ConditionEngineError,
  evaluateCondition,
  type ConditionContext,
} from "./conditions.ts"
export {
  CharacterConflictError,
  resolveNumericConflicts,
  type NumericConflictResolution,
} from "./conflicts.ts"
export {
  RESOLVED_CHARACTER_CONTRACT_VERSION,
  ResolvedCharacterContractError,
  hasResolvedDynamicSection,
  resolveCapabilities,
  resolveCharacterContract,
  resolvedDynamicSections,
  validateResolvedCharacterContract,
  type ResolvedCapabilities,
  type ResolvedCapabilitySectionKey,
  type ResolvedCharacterContract,
  type ResolvedDynamicSectionKey,
} from "./contract.ts"
export {
  CharacterEngineInputError,
  createCharacterEngineInput,
  validateCharacterEngineInput,
} from "./core.ts"
export {
  ExplainEngineError,
  explainCharacter,
  type CharacterExplainQuery,
  type CharacterExplanation,
  type ExplanationNode,
  type ExplanationNodeKind,
  type ExplanationStatus,
} from "./explain.ts"
export {
  FormulaConflictError,
  FormulaEngineError,
  evaluateFormula,
  selectFormula,
  validateFormula,
  type FormulaContext,
  type FormulaSelection,
} from "./formulas.ts"
export {
  GrantConflictError,
  GrantEngineError,
  grantIdentity,
  resolveGrantResolution,
  resolveGrants,
  resolveProficiencyRank,
  savingThrowProficiencyKey,
  skillProficiencyKey,
  type GrantIdentityMode,
  type GrantResolution,
  type ResolvedProficiencyRank,
} from "./grants.ts"
export {
  NumericEngineError,
  abilityModifier,
  applyNumericOperation,
  proficiencyBonusForLevel,
} from "./numeric.ts"
export {
  ResourceEngineError,
  applyResourceRecovery,
  parseResourceGrantPayload,
  resolveResources,
  resourceMaxTarget,
  resourceStateKey,
  spendResource,
} from "./resources.ts"
export { resolveCharacter, resolveCharacterInput } from "./resolver.ts"
export {
  SpellConflictError,
  SpellEngineError,
  applySpellResourceOption,
  parseSpellGrantPayload,
  resolveSpells,
  setSpellAccessPrepared,
  spellAccessStateKey,
  spellMethodAttackBonusTarget,
  spellMethodSaveDcTarget,
  spellPreparedFactKey,
} from "./spells.ts"
export {
  SuppressionEngineError,
  applySuppressions,
  type SuppressionResolution,
} from "./suppressions.ts"
export {
  TemporaryEffectEngineError,
  applyCharacterEvent,
  createTemporaryEffectController,
  createTemporaryEffectLifetime,
  eventSequence,
  eventSequenceFactKey,
  isTemporaryEffectExpired,
  remainingTemporaryEffectEvents,
  type TemporaryEffectController,
  type TemporaryEffectEvent,
  type TemporaryEffectLifetime,
  type TemporaryEffectSuppressionOptions,
} from "./temporary-effects.ts"
export {
  CHARACTER_ENGINE_STATUS,
  CHARACTER_ENGINE_VERSION,
  CHARACTER_ENGINE_VERSION_INFO,
} from "./version.ts"
export {
  ABILITY_KEYS,
  PASSIVE_KEYS,
  SKILL_KEYS,
  type AbilityKey,
  type ActionAttackDefinition,
  type ActionDamageDefinition,
  type ActionDice,
  type ActionGrantPayload,
  type ActionRange,
  type ActionResourceCost,
  type BaseCharacter,
  type CharacterCondition,
  type CharacterContribution,
  type CharacterEngineInput,
  type CharacterSource,
  type CharacterState,
  type FormulaContribution,
  type FormulaExpression,
  type FormulaTarget,
  type GrantContribution,
  type GrantPayload,
  type GrantTarget,
  type NumericContribution,
  type NumericOperation,
  type NumericTarget,
  type PassiveKey,
  type ProficiencyGrantPayload,
  type ProficiencyRank,
  type ResolvedAbility,
  type ResolvedAction,
  type ResolvedActionAttack,
  type ResolvedActionDamage,
  type ResolvedActionResourceCost,
  type ResolvedCharacter,
  type ResolvedFormulaNumber,
  type ResolvedGrant,
  type ResolvedNumber,
  type ResolvedResource,
  type ResolvedSavingThrow,
  type ResolvedSkill,
  type ResolvedSpell,
  type ResolvedSpellAccess,
  type ResolvedSpellCastingMethod,
  type ResolvedSpellResourceCost,
  type ResolvedSpellResourceOption,
  type ResourceGrantPayload,
  type ResourceRechargeRule,
  type ResourceRechargeTrigger,
  type ResourceState,
  type SenseGrantPayload,
  type SkillKey,
  type SpellCastingMethodDefinition,
  type SpellGrantPayload,
  type SpellIdentityDefinition,
  type SpellPreparationRule,
  type SpellResourceCost,
  type SpellResourceOption,
  type StateCondition,
  type StateFactValue,
  type SuppressionCondition,
  type SuppressionContribution,
  type SuppressionSelector,
} from "./types.ts"
