import assert from "node:assert/strict"
import fs from "node:fs"
import test from "node:test"

const app = fs.readFileSync("src/ui-v1-isolated/UiV1App.tsx", "utf8")
const entry = fs.readFileSync("src/ui-v1-isolated/main.tsx", "utf8")
const shell = fs.readFileSync("src/ui-v1-isolated/GMWorkshop.tsx", "utf8")
const main = fs.readFileSync("src/ui-v1-isolated/GMWorkshopMain.tsx", "utf8")
const review = fs.readFileSync("src/ui-v1-isolated/GMWorkshopReview.tsx", "utf8")
const members = fs.readFileSync("src/ui-v1-isolated/GMWorkshopMembers.tsx", "utf8")
const characters = fs.readFileSync("src/ui-v1-isolated/GMWorkshopCharacters.tsx", "utf8")
const library = fs.readFileSync("src/ui-v1-isolated/GMWorkshopLibrary.tsx", "utf8")
const materials = fs.readFileSync("src/ui-v1-isolated/GMWorkshopMaterials.tsx", "utf8")
const data = fs.readFileSync("src/ui-v1-isolated/useGMWorkshopData.ts", "utf8")
const actions = fs.readFileSync("src/ui-v1-isolated/gmWorkshopSnakeActions.ts", "utf8")
const styles = fs.readFileSync("src/ui-v1-isolated/gm-workshop.css", "utf8")
const workspaceData = fs.readFileSync("src/ui-v1-isolated/useWorkspaceData.ts", "utf8")
const sectionData = fs.readFileSync("src/ui-v1-isolated/useUiV1SectionData.ts", "utf8")
const migration = fs.readFileSync(
  "supabase/migrations/20260913150723_gm_workshop_character_drafts_v1.sql",
  "utf8",
)
const partyAdminMigration = fs.readFileSync(
  "supabase/migrations/20260913193451_gm_party_member_and_invite_admin_v1.sql",
  "utf8",
)
const characterView = fs.readFileSync("src/ui-v1-isolated/CharacterView.tsx", "utf8")
const stage3Migration = fs.readFileSync(
  "supabase/migrations/20260920070533_gm_workshop_definition_lifecycle_stage3.sql",
  "utf8",
)
const materialStage3Migration = fs.readFileSync(
  "supabase/migrations/20260920071633_gm_workspace_material_integrity_stage3.sql",
  "utf8",
)
const referenceTypes = fs.readFileSync("src/reference-engine/types.ts", "utf8")
const referenceStorage = fs.readFileSync("src/reference-engine/supabase.ts", "utf8")
const definitionRuntime = fs.readFileSync("src/ui-v1-isolated/gmWorkshopDefinitionRuntime.ts", "utf8")

test("UI 1.0 management route is the real GM Workshop and uses destination panels instead of legacy tabs", () => {
  assert.match(app, /<GMWorkshop/)
  assert.match(app, /const workshopSections: WorkshopSection\[\] = \["review", "members", "characters", "library", "materials"\]/)
  assert.match(app, /workspace\/manage\/party[\s\S]*section: "members"/)
  assert.match(app, /workspace\/manage\/draft[\s\S]*section: "review"/)
  assert.match(app, /path\.startsWith\("workspace\/manage\/"\)/)
  assert.match(app, /"workspace\/manage\/" \+ section/)
  assert.match(entry, /\.\/gm-workshop\.css/)
  assert.match(shell, /GMWorkshopMain/)
  assert.match(main, /title="На проверку"/)
  assert.match(main, /title="Участники"/)
  assert.match(main, /title="Персонажи"/)
  assert.match(main, /title="Библиотека"/)
  assert.match(main, /title="Личные материалы"/)
  assert.ok(main.indexOf('title="На проверку"') < main.indexOf('title="Участники"'))
  assert.doesNotMatch(
    main + review + members + characters + library + materials,
    /role="tab"|gm-primary-nav|gm-subrail/,
  )
})

test("draft lifecycles live with their domains while review only contains AI proposals", () => {
  assert.match(migration, /publication_state text/)
  assert.match(migration, /check \(publication_state in \('draft','campaign'\)\)/)
  assert.match(migration, /set_character_publication_state_v1/)
  assert.match(data, /publication_state: "draft"/)
  assert.match(data, /oracle\.characters\.setPublicationState/)
  assert.match(characters, /Черновики/)
  assert.match(characters, /createDraftCharacter/)
  assert.match(library, /Черновики/)
  assert.match(library, /createDraftDefinition/)
  assert.match(review, /AI · REVIEW/)
  assert.match(review, /applyAIDraft/)
  assert.doesNotMatch(review, /createDraftCharacter|createDraftDefinition/)
  assert.match(workspaceData, /\.eq\("publication_state", "campaign"\)/)
  assert.match(sectionData, /\.eq\("publication_state", "campaign"\)/)
})

test("PC assignment and active identity remain separate commands", () => {
  assert.match(data, /assignCharacter/)
  assert.match(data, /oracle\.characters\.update/)
  assert.match(data, /setActiveCharacter/)
  assert.match(data, /oracle\.characters\.setActive/)
  assert.match(actions, /Персонаж назначен\. Активность выбирается отдельно/)
  assert.match(members, /Сделать активным/)
  assert.match(migration, /publication_state = 'campaign'/)
  assert.match(migration, /Dead character cannot be active/)
})

test("Participants owns people and assignments without duplicating the global character catalog", () => {
  assert.match(members, /Участники кампании/)
  assert.match(members, /Назначенные PC/)
  assert.match(members, /createWorkshopMemberActions/)
  assert.match(members, /createWorkshopMemberAssignAction/)
  assert.match(members, /createWorkshopMemberSetActiveAction/)
  assert.match(members, /createWorkshopMemberUnassignAction/)
  assert.doesNotMatch(members, /Все персонажи игроков/)
  assert.doesNotMatch(members, /createWorkshopCharacterActions/)
  assert.doesNotMatch(members, /createWorkshopPcUnassignAction/)
  assert.match(characters, /campaignCharacters/)
  assert.match(actions, /id: "assign-free-pc"/)
  assert.match(actions, /id: "active-character"/)
  assert.match(actions, /createWorkshopMemberUnassignAction/)
})

test("Workshop character creation uses real class templates instead of a free-text class field", () => {
  assert.match(characters, /classTemplateId/)
  assert.match(characters, /data\.classTemplates\.map/)
  assert.doesNotMatch(characters, /id: "characterClass"/)
  assert.match(data, /oracle\.characters\.assignTemplate/)
  assert.match(data, /existing\?\.selected_choices \|\| \{\}/)
  assert.match(actions, /id: "classes"/)
  assert.match(actions, /label: "Выбрать класс"|label: classAssignments\.length \? "Добавить ещё класс" : "Выбрать класс"/)
  assert.match(actions, /Выбрать подкласс/)
  assert.match(actions, /removeTemplateAssignment/)
})

test("Character View is a real GM-aware sheet surface instead of a placeholder route", () => {
  assert.match(app, /<CharacterView/)
  assert.match(characterView, /createWorkshopCharacterActions/)
  assert.match(characterView, /control\.canManage && workshopCharacter/)
  assert.match(characterView, /const managerActions/)
  assert.match(characterView, /<CharacterSheetShell/)
  assert.match(characterView, /<CharacterInventoryInterface/)
  assert.match(characterView, /<CharacterSheetSpells/)
  assert.match(characterView, /<CharacterSheetFeatures/)
  assert.match(actions, /id: "edit-character"/)
  assert.match(actions, /label: "Редактировать"/)
  assert.match(actions, /id: "convert-character-type"/)
  assert.match(data, /convertCharacterType/)
  assert.match(data, /oracle\.characters\.convertType/)
  assert.doesNotMatch(actions, /id: "characterType"/)
})

test("Workshop participant and invite management are first-class Snake actions", () => {
  assert.match(members, /createWorkshopMemberActions/)
  assert.match(members, /type: "campaign-member"/)
  assert.match(members, /type: "campaign-invite"/)
  assert.match(actions, /createWorkshopMemberAssignAction/)
  assert.match(actions, /createWorkshopMemberRoleAction/)
  assert.match(actions, /id: "active-character"/)
  assert.match(actions, /id: "clear-active"/)
  assert.match(actions, /createWorkshopInviteActions/)
  assert.match(actions, /id: "copy-invite"/)
  assert.match(actions, /id: "create-invite"/)
  assert.match(actions, /id: "revoke-invite"/)
  assert.match(actions, /id: "remove-member"/)
  assert.match(members, /История приглашений/)
  assert.match(data, /oracle\.campaign\.setMemberRole/)
  assert.match(data, /oracle\.campaign\.removeMember/)
  assert.match(data, /oracle\.campaign\.createInvite/)
  assert.match(data, /oracle\.campaign\.revokeInvite/)
  assert.match(partyAdminMigration, /remove_campaign_member_v1/)
  assert.match(partyAdminMigration, /revoke_campaign_invite_v1/)
})

test("Workshop character Snake provider covers the current management lifecycle", () => {
  assert.match(actions, /createWorkshopCharacterEditAction/)
  assert.match(actions, /id: "edit-character"/)
  assert.match(actions, /createWorkshopDraftCharacterDeleteAction/)
  assert.match(actions, /id: "delete-draft-character"/)
  assert.match(actions, /id: "access"/)
  assert.match(actions, /id: "visibility"/)
  assert.match(actions, /id: "state"/)
  assert.match(data, /updateCharacter/)
  assert.match(data, /oracle\.characters\.update/)
  assert.match(data, /deleteCharacter/)
  assert.match(data, /oracle\.characters\.delete/)
})

test("Workshop definitions, folders and materials expose reversible management through Snake", () => {
  assert.match(actions, /id: "open-definition"/)
  assert.match(actions, /id: "restore"/)
  assert.match(actions, /id: "unlink-item"/)
  assert.match(materials, /id: "open-folder"/)
  assert.match(materials, /id: "rename-folder"/)
  assert.match(materials, /id: "move-folder"/)
  assert.match(materials, /id: "delete-folder"/)
  assert.match(materials, /id: "open-material"/)
  assert.match(materials, /id: "edit-note"/)
  assert.match(materials, /id: "move-material"/)
  assert.match(materials, /id: "rename-material"/)
  assert.match(materials, /id: "move-up"/)
  assert.match(materials, /id: "move-down"/)
  assert.match(materials, /id: "delete-material"/)
  assert.match(data, /moveFolder/)
  assert.match(data, /moveMaterial/)
  assert.match(data, /renameMaterial/)
  assert.match(data, /reorderFolder/)
  assert.match(actions, /id: "mechanicsJson"/)
  assert.match(actions, /JSON\.parse\(rawMechanics\)/)
  assert.match(actions, /Механики должны быть JSON-массивом/)
})

test("published NPC visibility supports immediate visibility or encounter discovery", () => {
  assert.match(actions, /label: "При встрече"/)
  assert.match(actions, /label: "Видно сразу"/)
  assert.match(data, /setNpcVisibility/)
  assert.match(data, /oracle\.characters\.setVisibility/)
  assert.match(data, /oracle\.world\.setNpcHabitat/)
  assert.match(actions, /id: "habitats"/)
  assert.match(migration, /character_npc_discoveries/)
  assert.match(migration, /visibility_mode = 'discover'/)
  assert.match(migration, /visibility_mode = 'always'/)
})

test("character catalog is one searchable PC plus NPC workspace with filters and recent destinations", () => {
  assert.match(characters, /Найти персонажа, класс, игрока/)
  assert.match(characters, /Все персонажи/)
  assert.match(characters, /Персонажи игроков/)
  assert.match(characters, /Персонажи мира/)
  assert.match(characters, /Свободные/)
  assert.match(characters, /Мёртвые/)
  assert.match(characters, /Недавние/)
  assert.match(characters, /campaignCharacters/)
  assert.doesNotMatch(characters, /characterKind|setCharacterKind/)
})

test("library owns the full definition lifecycle and publishes staged revisions atomically", () => {
  assert.match(library, /Черновики/)
  assert.match(library, /Рабочая база/)
  assert.match(library, /Архив/)
  assert.match(data, /revises_definition_id/)
  assert.match(data, /oracle\.definitions\.publishDraft/)
  assert.match(referenceTypes, /definition\.publish_draft/)
  assert.match(referenceStorage, /publish_reference_definition_draft_v1/)
  assert.match(stage3Migration, /publish_reference_definition_draft_v1/)
  assert.match(stage3Migration, /Target definition must be active/)
  assert.match(stage3Migration, /current_revision = v_target_revision/)
  assert.match(actions, /Создать ревизию/)
  assert.match(actions, /Опубликовать ревизию/)
})

test("linked item mechanics stay as revision references and compile only when an item is issued", () => {
  assert.match(data, /linked_definitions/)
  assert.match(definitionRuntime, /linked_definition_refs/)
  assert.match(definitionRuntime, /chasovoy\.getDefinition/)
  assert.match(data, /compileWorkshopItemInput/)
  assert.doesNotMatch(data, /chasovoy\.getDefinition/)
  assert.match(actions, /Привязать к предмету/)
  assert.match(actions, /linkedDefinitionIds/)
})

test("runtime feature issuance preserves definition semantics and provenance", () => {
  assert.match(definitionRuntime, /definition\.kind === "condition"[\s\S]*"effect"/)
  assert.match(definitionRuntime, /definition\.kind === "feat"[\s\S]*"feat"/)
  assert.match(definitionRuntime, /source_definition_id: definition\.id/)
  assert.match(definitionRuntime, /source_definition_revision: definition\.revision/)
  assert.match(definitionRuntime, /source_definition_kind: definition\.kind/)
  assert.match(data, /workshopFeatureInput/)
  assert.match(stage3Migration, /source_definition_kind in \('feature','feat','condition'\)/)
})

test("definition runtime projection is extracted from the GM Workshop god-hook", () => {
  assert.match(definitionRuntime, /compileWorkshopItemInput/)
  assert.match(definitionRuntime, /workshopSpellInput/)
  assert.match(definitionRuntime, /workshopFeatureInput/)
  assert.doesNotMatch(data, /function itemInput|function spellInput|function definitionWeightKg/)
})

test("personal GM materials are explicit and folder mutations are transactional", () => {
  assert.match(data, /uploadCampaignFile/)
  assert.match(data, /deleteCampaignMediaObject/)
  assert.match(data, /createNote/)
  assert.match(data, /updateNote/)
  assert.match(data, /createFolder/)
  assert.match(data, /renameFolder/)
  assert.match(data, /reorder_gm_workspace_folder_v1/)
  assert.match(data, /delete_gm_workspace_folder_v1/)
  assert.match(materials, /Личные материалы · только ты/)
  assert.match(materials, /Дочерние папки сохранятся и поднимутся на уровень выше/)
  assert.match(materials, /\+ Заметка/)
  assert.match(materials, /\+ Папка/)
  assert.match(materials, /\+ Файл/)
  assert.match(materials, /type="file"/)
  assert.match(materials, /window\.open\(material\.fileUrl/)
  assert.match(styles, /\.u1-gm-material-upload/)
  assert.match(materialStage3Migration, /gm_workspace_folders_parent_workspace_fkey/)
  assert.match(materialStage3Migration, /gm_workspace_files_folder_workspace_fkey/)
  assert.match(materialStage3Migration, /on delete restrict/)
  assert.match(materialStage3Migration, /reorder_gm_workspace_folder_v1/)
  assert.match(materialStage3Migration, /delete_gm_workspace_folder_v1/)
  assert.match(materialStage3Migration, /set parent_id = v_folder\.parent_id/)
  assert.match(materialStage3Migration, /set folder_id = null/)
})

test("successful Workshop mutation is not reported as failed when refresh fails", () => {
  assert.match(data, /refreshError/)
  assert.match(data, /Изменение сохранено, но экран не удалось обновить/)
  assert.match(data, /await action\(\)[\s\S]*try \{[\s\S]*await load\(\)[\s\S]*ok: true/)
})
