import { useState } from "react"
import type { FormEvent } from "react"
import { useRooms } from "../hooks/useRooms"
import { useCharacters } from "../context/CharacterContext"
import CampaignImage from "../components/common/CampaignImage"
import ImageUploadField from "../components/common/ImageUploadField"
import ContextActionSheet,{type ContextAction} from "../components/common/ContextActionSheet"
import type { ChatRoom } from "../types/chat"
import { useLongPressItem } from "../hooks/useLongPressItem"
import { deleteCampaignMediaObject } from "../lib/mediaUpload"

type Props={onOpenRoom:(id:string)=>void}
type Editor={mode:"create"}|{mode:"edit";room:ChatRoom}|null

export default function Chats({onOpenRoom}:Props){
  const{canManage,campaignId}=useCharacters();const rooms=useRooms();const[editor,setEditor]=useState<Editor>(null);const[title,setTitle]=useState("");const[avatar,setAvatar]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[menu,setMenu]=useState<ChatRoom|null>(null);const[deleteTarget,setDeleteTarget]=useState<ChatRoom|null>(null)
  const bind=useLongPressItem<ChatRoom>((room)=>setMenu(room))
  const flood=rooms.rooms.filter((room)=>room.category==="flood");const game=rooms.rooms.filter((room)=>room.category==="game")
  function openCreate(){setTitle("");setAvatar("");setError("");setEditor({mode:"create"})}
  function openEdit(room:ChatRoom){setTitle(room.title);setAvatar(room.avatar_url||"");setError("");setEditor({mode:"edit",room})}
  async function closeEditor(){if(editor?.mode==="create"&&avatar)await deleteCampaignMediaObject(avatar);if(editor?.mode==="edit"&&avatar&&avatar!==editor.room.avatar_url)await deleteCampaignMediaObject(avatar);setEditor(null)}
  async function save(event:FormEvent){event.preventDefault();if(!editor||!title.trim())return;setSaving(true);setError("")
    if(editor.mode==="create"){const result=await rooms.createGameRoom(title);if(!result.ok||!result.id){setSaving(false);setError(result.error||"Не удалось создать чат.");return}if(avatar){const art=await rooms.setRoomAvatar(result.id,avatar);if(!art.ok){setSaving(false);setError(art.error||"Чат создан, но арт не сохранился.");return}}setSaving(false);setEditor(null);onOpenRoom(result.id);return}
    const oldAvatar=editor.room.avatar_url;const rename=await rooms.renameRoom(editor.room.id,title);if(!rename.ok){setSaving(false);setError(rename.error||"Не удалось сохранить.");return}const art=await rooms.setRoomAvatar(editor.room.id,avatar||null);setSaving(false);if(!art.ok){setError(art.error||"Не удалось сохранить арт.");return}if(oldAvatar&&oldAvatar!==avatar)void deleteCampaignMediaObject(oldAvatar);setEditor(null)
  }
  async function remove(room:ChatRoom){setSaving(true);setError("");const result=await rooms.deleteRoom(room.id);setSaving(false);if(!result.ok){setError(result.error||"Не удалось удалить чат.");return}if(room.avatar_url)void deleteCampaignMediaObject(room.avatar_url);setDeleteTarget(null)}
  function actions(room:ChatRoom):ContextAction[]{return[{id:"open",label:"Открыть",detail:"Перейти в чат",icon:"↗",onSelect:()=>onOpenRoom(room.id)},...(canManage&&room.category==="game"?[{id:"edit",label:"Настроить",detail:"Название и арт чата",icon:"✎",onSelect:()=>openEdit(room)},{id:"delete",label:"Удалить чат",detail:"Сообщения и вложения будут удалены",icon:"×",danger:true,onSelect:()=>setDeleteTarget(room)}]:[])]}
  function list(items:ChatRoom[]){return <div className="chat-v2-list">{items.map((room)=><article {...bind(room)} style={{touchAction:"pan-y"}} className="chat-v2-list-row" key={room.id}><button type="button" className="chat-v2-room" onClick={()=>onOpenRoom(room.id)}><span className="chat-v2-room-art">{room.avatar_url?<CampaignImage value={room.avatar_url} alt=""/>:<span>{room.category==="flood"?"◌":room.title.slice(0,1).toUpperCase()}</span>}</span><span className="chat-v2-room-copy"><span><strong>{room.title}</strong><time>{room.time}</time></span><small>{room.preview}</small></span>{room.unread_count>0&&<em>{room.unread_count>99?"99+":room.unread_count}</em>}</button>{canManage&&room.category==="game"&&<button className="chat-v2-room-menu" type="button" onClick={()=>setMenu(room)}>•••</button>}</article>)}{!items.length&&<div className="v2-empty-state"><span>◌</span><strong>Здесь пока пусто</strong><p>Создай первую игровую сцену.</p></div>}</div>}
  if(rooms.loading)return <div className="center-state"><span className="status-spinner"/><span>Загружаем чаты…</span></div>
  return <><div className="chats-v2 page-stack">{(error||rooms.error)&&<div className="auth-error">{error||rooms.error}</div>}<section className="section chats-v2-section"><div className="section-head"><div><h3 className="section-title">Флуд</h3><p className="item-meta">Общий разговор кампании</p></div></div>{list(flood)}</section><section className="section chats-v2-section"><div className="section-head"><div><h3 className="section-title">Игровые сцены</h3><p className="item-meta">Отдельные комнаты с доступом и своим артом</p></div>{canManage&&<button className="section-link" type="button" onClick={openCreate}>＋ Чат</button>}</div>{list(game)}</section></div>
    {editor&&<div className="sheet-backdrop" onMouseDown={()=>void closeEditor()}><form className="bottom-sheet v2-editor-sheet chat-room-editor-v2" onSubmit={save} onMouseDown={(e)=>e.stopPropagation()}><div className="sheet-handle"/><header className="v2-sheet-head"><div><span>Игровая сцена</span><h3>{editor.mode==="create"?"Новый чат":"Настройки чата"}</h3><p>Арт работает как аватар комнаты в общем списке.</p></div><button type="button" onClick={()=>void closeEditor()}>×</button></header><section className="v2-form-section"><label className="field-label">Название</label><input className="app-input" value={title} onChange={(e)=>setTitle(e.target.value)} maxLength={100} autoFocus/><ImageUploadField value={avatar} onChange={setAvatar} folder="chat-avatars" campaignId={campaignId} label="Арт чата" hint="Квадратное превью для списка комнат" crop="square"/></section>{error&&<div className="auth-error">{error}</div>}<button className="v2-primary-button v2-full-button" type="submit" disabled={saving||!title.trim()}>{saving?"Сохраняем…":editor.mode==="create"?"Создать чат":"Сохранить"}</button></form></div>}
    {menu&&<ContextActionSheet title={menu.title} subtitle="Действия с чатом" actions={actions(menu)} onClose={()=>setMenu(null)}/>} {deleteTarget&&<div className="sheet-backdrop" onMouseDown={()=>setDeleteTarget(null)}><section className="bottom-sheet v2-confirm" onMouseDown={(e)=>e.stopPropagation()}><div className="sheet-handle"/><span className="v2-confirm-icon">×</span><h3>Удалить «{deleteTarget.title}»?</h3><p>Комната, сообщения и вложения исчезнут без восстановления.</p><div><button type="button" onClick={()=>setDeleteTarget(null)}>Отмена</button><button type="button" className="is-danger" disabled={saving} onClick={()=>void remove(deleteTarget)}>{saving?"Удаляем…":"Удалить"}</button></div></section></div>}
  </>
}
