-- CLASS_MIGRATION_SCOPE: infrastructure
-- Add the one PHB 2024 spell referenced by the certified Moon Druid package
-- that was missing from spell_catalog. This is catalog metadata/runtime linkage,
-- not a rewrite of the class package.

insert into public.spell_catalog(
  slug,
  name_en,
  name_ru,
  spell_level,
  school,
  casting_time,
  spell_range,
  area,
  duration,
  components,
  material,
  concentration,
  ritual,
  check_type,
  damage,
  effect_summary,
  upcast,
  notes,
  rules_text,
  source,
  source_kind,
  license,
  sort_order,
  author_description,
  author_comment,
  material_cost_gp,
  material_consumed,
  material_consumption,
  roll_mode,
  roll_recipe
)
values(
  'fount-of-moonlight',
  'Fount of Moonlight',
  'Источник лунного света',
  4,
  'Evocation',
  'Действие',
  'На себя',
  'Яркий свет 20 футов; тусклый свет ещё 20 футов',
  'Концентрация, до 10 минут',
  array['В','С']::text[],
  null,
  true,
  false,
  'Спасбросок Телосложения для ответной реакции',
  '+2к6 излучением к рукопашным атакам',
  'Лунный свет окружает заклинателя, даёт сопротивление излучению, усиливает рукопашные попадания и позволяет реакцией ослепить видимого нападающего при провале спасброска Телосложения.',
  '',
  'Ответная реакция доступна после получения урона от видимого существа в пределах 60 футов.',
  null,
  'Player''s Handbook 2024',
  'official',
  null,
  0,
  'Лунное усиление для ближнего боя с защитой от излучения и ответной реакцией на полученный урон.',
  'Круг Луны получает это заклинание подготовленным; запись нужна прежде всего для канонической spell-ссылки и серверной проверки уровня.',
  null,
  false,
  'none',
  'contextual',
  null
)
on conflict(slug) do update set
  name_en=excluded.name_en,
  name_ru=excluded.name_ru,
  spell_level=excluded.spell_level,
  school=excluded.school,
  casting_time=excluded.casting_time,
  spell_range=excluded.spell_range,
  area=excluded.area,
  duration=excluded.duration,
  components=excluded.components,
  concentration=excluded.concentration,
  ritual=excluded.ritual,
  check_type=excluded.check_type,
  damage=excluded.damage,
  effect_summary=excluded.effect_summary,
  notes=excluded.notes,
  source=excluded.source,
  source_kind=excluded.source_kind,
  author_description=excluded.author_description,
  author_comment=excluded.author_comment,
  roll_mode=excluded.roll_mode,
  updated_at=now();
